"""nullable fields on file chunk

Revision ID: 15753d4780c4
Revises: 9de167191144
Create Date: 2026-07-24 21:47:52.596668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15753d4780c4'
down_revision: Union[str, Sequence[str], None] = '9de167191144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('file_chunks', 'chunk_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('file_chunks', 'chunk_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('file_chunks', 'telegram_message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('file_chunks', 'telegram_file_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('file_chunks', 'telegram_unique_file_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_chunks', 'telegram_unique_file_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('file_chunks', 'telegram_file_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('file_chunks', 'telegram_message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('file_chunks', 'chunk_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('file_chunks', 'chunk_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('file_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
