"""add file mime type and remove unused fields

Revision ID: 24c7d08fde8b
Revises: 15753d4780c4
Create Date: 2026-07-28 09:37:30.619408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c7d08fde8b'
down_revision: Union[str, Sequence[str], None] = '15753d4780c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_chunks', 'telegram_unique_file_id')
    op.drop_column('file_chunks', 'telegram_file_id')
    op.add_column('files', sa.Column('mimetype', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'mimetype')
    op.add_column('file_chunks', sa.Column('telegram_file_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file_chunks', sa.Column('telegram_unique_file_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
