"""add file chunk models

Revision ID: 5037d7f20a12
Revises: d10153623610
Create Date: 2026-07-24 21:04:24.475386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5037d7f20a12'
down_revision: Union[str, Sequence[str], None] = 'd10153623610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_chunks',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_hash', sa.String(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=False),
    sa.Column('telegram_file_id', sa.String(), nullable=False),
    sa.Column('telegram_unique_file_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_chunks_file_id'), 'file_chunks', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_chunks_file_id'), table_name='file_chunks')
    op.drop_table('file_chunks')
    # ### end Alembic commands ###
