"""filesize and filepath can be null now

Revision ID: d10153623610
Revises: 988393ad83fa
Create Date: 2026-07-24 15:58:52.599035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10153623610'
down_revision: Union[str, Sequence[str], None] = '988393ad83fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'filesize',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('files', 'filepath',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'filepath',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('files', 'filesize',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
