"""vault and user relation

Revision ID: d27d35f8a5d4
Revises: 24c7d08fde8b
Create Date: 2026-07-28 11:30:30.422758

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d27d35f8a5d4"
down_revision: Union[str, Sequence[str], None] = "24c7d08fde8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("picture", sa.String(), nullable=True))
    op.add_column("vaults", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_vaults_user_id"), "vaults", ["user_id"], unique=False)
    op.create_foreign_key(None, "vaults", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vaults", type_="foreignkey")
    op.drop_index(op.f("ix_vaults_user_id"), table_name="vaults")
    op.drop_column("vaults", "user_id")
    op.drop_column("users", "picture")
    # ### end Alembic commands ###
