"""file status and file field changes

Revision ID: ff80ed55a6b2
Revises: b9a407d7092e
Create Date: 2026-07-24 15:53:37.800039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff80ed55a6b2"
down_revision: Union[str, Sequence[str], None] = "b9a407d7092e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    file_status_enum = postgresql.ENUM(
        "RECEIVING",
        "STORED_LOCALLY",
        "QUEUED",
        "PUSHING",
        "COMPLETE",
        "FAILED",
        name="filestatus",
    )

    file_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "files",
        sa.Column(
            "status",
            file_status_enum,
            nullable=False,
            server_default="RECEIVING",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "status")
    # ### end Alembic commands ###
