services:
  telegram-bot-api:
    image: evilfreelancer/docker-telegram-bot-api:latest
    container_name: tg-bot-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - ./tg-bot-api-data:/var/lib/telegram-bot-api
